---
abstract: 'Filter and validate data values'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Class::Null: '1.09'
  Module::Build: '0.4004'
  version: '0.88'
configure_requires:
  Module::Build: '0.4004'
  version: '0.88'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Validation
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Data::Validation:
    file: lib/Data/Validation.pm
    version: v0.16.5
  Data::Validation::Constants:
    file: lib/Data/Validation/Constants.pm
    version: v0.16.5
  Data::Validation::Constraints:
    file: lib/Data/Validation/Constraints.pm
    version: v0.16.5
  Data::Validation::Constraints::Date:
    file: lib/Data/Validation/Constraints/Date.pm
    version: v0.16.5
  Data::Validation::Constraints::Email:
    file: lib/Data/Validation/Constraints/Email.pm
    version: v0.16.5
  Data::Validation::Constraints::Password:
    file: lib/Data/Validation/Constraints/Password.pm
    version: v0.16.5
  Data::Validation::Constraints::Path:
    file: lib/Data/Validation/Constraints/Path.pm
    version: v0.16.5
  Data::Validation::Constraints::Postcode:
    file: lib/Data/Validation/Constraints/Postcode.pm
    version: v0.16.5
  Data::Validation::Constraints::URL:
    file: lib/Data/Validation/Constraints/URL.pm
    version: v0.16.5
  Data::Validation::Exception:
    file: lib/Data/Validation/Exception.pm
    version: v0.16.5
  Data::Validation::Filters:
    file: lib/Data/Validation/Filters.pm
    version: v0.16.5
  Data::Validation::Utils:
    file: lib/Data/Validation/Utils.pm
    version: v0.16.5
recommends:
  Class::Usul: v0.38.0
requires:
  Email::Valid: '1.194'
  Exporter::Tiny: 0.041_02
  LWP::UserAgent: '2.036'
  Module::Runtime: '0.014'
  Moo: '1.006000'
  Regexp::Common: '2013031301'
  Try::Tiny: '0.22'
  Unexpected: v0.33.0
  namespace::autoclean: '0.19'
  perl: '5.010001'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Validation
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.16.5
