---
abstract: 'Filter and check data values'
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  Class::Null: 1.09
  Exception::Class: 1.23
  Test::More: 0.74
  Test::Pod: 1.26
configure_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Build: 0.36
  version: 0.74
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validation
no_index:
  directory:
    - t
provides:
  Data::Validation:
    file: lib/Data/Validation.pm
    version: 0.5.120
  Data::Validation::Constraints:
    file: lib/Data/Validation/Constraints.pm
    version: 0.5.120
  Data::Validation::Constraints::Date:
    file: lib/Data/Validation/Constraints/Date.pm
    version: 0.5.120
  Data::Validation::Constraints::Email:
    file: lib/Data/Validation/Constraints/Email.pm
    version: 0.5.120
  Data::Validation::Constraints::Password:
    file: lib/Data/Validation/Constraints/Password.pm
    version: 0.5.120
  Data::Validation::Constraints::Path:
    file: lib/Data/Validation/Constraints/Path.pm
    version: 0.5.120
  Data::Validation::Constraints::Postcode:
    file: lib/Data/Validation/Constraints/Postcode.pm
    version: 0.5.120
  Data::Validation::Constraints::URL:
    file: lib/Data/Validation/Constraints/URL.pm
    version: 0.5.120
  Data::Validation::Filters:
    file: lib/Data/Validation/Filters.pm
    version: 0.5.120
  Data::Validation::Utils:
    file: lib/Data/Validation/Utils.pm
    version: 0.5.120
recommends:
  CatalystX::Usul::Time: 0.3.576
requires:
  Class::MOP: 0.53
  Email::Valid: 0.179
  LWP::UserAgent: 2.036
  List::Util: 1.19
  Moose: 0.38
  Moose::Role: 0.55
  Moose::Util::TypeConstraints: 0.21
  Regexp::Common: 2.120
  Scalar::Util: 1.19
  charnames: 1.05
  namespace::autoclean: 0.05
  perl: 5.008
  version: 0.74
resources:
  license: http://dev.perl.org/licenses/
version: 0.5.120
