---
abstract: 'Filter and check data values'
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  Class::Null: 1.09
  Exception::Class: 1.23
  Test::More: 0.74
  Test::Pod: 1.26
configure_requires:
  Module::Build: 0.32
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validation
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Data::Validation:
    file: lib/Data/Validation.pm
    version: v0.9.164
  Data::Validation::Constraints:
    file: lib/Data/Validation/Constraints.pm
    version: v0.9.160
  Data::Validation::Constraints::Date:
    file: lib/Data/Validation/Constraints/Date.pm
    version: v0.9.160
  Data::Validation::Constraints::Email:
    file: lib/Data/Validation/Constraints/Email.pm
    version: v0.9.160
  Data::Validation::Constraints::Password:
    file: lib/Data/Validation/Constraints/Password.pm
    version: v0.9.160
  Data::Validation::Constraints::Path:
    file: lib/Data/Validation/Constraints/Path.pm
    version: v0.9.160
  Data::Validation::Constraints::Postcode:
    file: lib/Data/Validation/Constraints/Postcode.pm
    version: v0.9.160
  Data::Validation::Constraints::URL:
    file: lib/Data/Validation/Constraints/URL.pm
    version: v0.9.160
  Data::Validation::Filters:
    file: lib/Data/Validation/Filters.pm
    version: v0.9.160
  Data::Validation::Utils:
    file: lib/Data/Validation/Utils.pm
    version: v0.9.160
recommends:
  Class::Usul::Time: v0.1.0
requires:
  Email::Valid: 0.179
  LWP::UserAgent: 2.036
  List::Util: 1.19
  Moose: 2.0402
  Regexp::Common: 2.12
  Scalar::Util: 1.19
  Try::Tiny: 0.09
  charnames: 1.05
  namespace::autoclean: 0.05
  perl: 5.01
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Validation
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: 0.9.164
