---
abstract: 'Filter and validate data values'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Class::Null: 1.09
  Module::Build: 0.4004
  Test::Pod: 1.26
  Unexpected: v0.6.0
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validation
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Data::Validation:
    file: lib/Data/Validation.pm
    version: v0.14.1
  Data::Validation::Constraints:
    file: lib/Data/Validation/Constraints.pm
    version: v0.14.1
  Data::Validation::Constraints::Date:
    file: lib/Data/Validation/Constraints/Date.pm
    version: v0.14.1
  Data::Validation::Constraints::Email:
    file: lib/Data/Validation/Constraints/Email.pm
    version: v0.14.1
  Data::Validation::Constraints::Password:
    file: lib/Data/Validation/Constraints/Password.pm
    version: v0.14.1
  Data::Validation::Constraints::Path:
    file: lib/Data/Validation/Constraints/Path.pm
    version: v0.14.1
  Data::Validation::Constraints::Postcode:
    file: lib/Data/Validation/Constraints/Postcode.pm
    version: v0.14.1
  Data::Validation::Constraints::URL:
    file: lib/Data/Validation/Constraints/URL.pm
    version: v0.14.1
  Data::Validation::Filters:
    file: lib/Data/Validation/Filters.pm
    version: v0.14.1
  Data::Validation::Utils:
    file: lib/Data/Validation/Utils.pm
    version: v0.14.1
recommends:
  Class::Usul: v0.22.0
requires:
  Class::Load: 0.18
  Email::Valid: 0.184
  LWP::UserAgent: 2.036
  Moo: 1.003000
  Regexp::Common: 2010010201
  Try::Tiny: 0.09
  Unexpected: v0.6.0
  namespace::sweep: 0.006
  perl: 5.010001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Validation
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.14.1
